### ISSUE TITLE
MooU2 App

### ISSUE THREAD

**Issue by ghost** [Infragistics/xamarin-forms-samples#1]
I am having trouble with the sample app. NuGet keeps trying to look for v17.1.100 of Infragistics, but I have v17.2.0. and it throws this error on all the Infragistics packages

Error		NuGet Package restore failed for project Moo2U.Droid: Unable to find version '17.1.1000' of package 'Infragistics.XF.DV'.
  C:\Users\Public\Documents\Infragistics\NuGet\: Package 'Infragistics.XF.DV.17.1.1000' is not found on source 'C:\Users\Public\Documents\Infragistics\NuGet\'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Infragistics.XF.DV.17.1.1000' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Infragistics.XF.DV.17.1.1000' is not found on source 'https://api.nuget.org/v3/index.json'.
  http://reactjs.net/packages/: Package 'Infragistics.XF.DV.17.1.1000' is not found on source 'http://reactjs.net/packages/'.
.

**Comment by brianlagunas** [comment]
This is not the official Moo2U app. We are experimenting with GitHub and our sample apps.  Though, you should be using the Infragistics NuGet feed in order to restore the current packages.

https://www.infragistics.com/help/xamarin/infragistics-nuget-feed
